spring:
  application:
    name: user-events
  cloud:
    stream:
      default:
        consumer:
          use-native-encoding: true
        producer:
          use-native-encoding: true
      bindings:
        user-input:
          destination: stream.users
          group: ${spring.application.name}
      default-binder: kafka
      kafka:
        binder:
          value:
            deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
          key:
            deserializer: org.apache.kafka.common.serialization.StringDeserializer
  kafka:
    properties:
      schema:
        registry:
          url: http://localhost:8081
      specific:
        avro:
          reader: true


